/** @type {import('ts-jest').JestConfigWithTsJest} */
export default {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest-setup.ts'],
  moduleDirectories: ['node_modules', 'src'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '.+\\.(png|jpg)$': 'identity-obj-proxy',
    '^@assets(.*)$': '<rootDir>/src/assets$1',
    '^@components(.*)$': '<rootDir>/src/components$1',
    '^@common(.*)$': '<rootDir>/src/components/common$1',
    '^@constants(.*)$': '<rootDir>/src/constants$1',
    '^@contexts(.*)$': '<rootDir>/src/contexts$1',
    '^@hocs(.*)$': '<rootDir>/src/hocs$1',
    '^@hooks(.*)$': '<rootDir>/src/hooks$1',
    '^@interfaces(.*)$': '<rootDir>/src/interfaces$1',
    '^@layouts(.*)$': '<rootDir>/src/layouts$1',
    '^@mocks(.*)$': '<rootDir>/src/mocks$1',
    '^@pages(.*)$': '<rootDir>/src/pages$1',
    '^@providers(.*)$': '<rootDir>/src/providers$1',
    '^@routes(.*)$': '<rootDir>/src/routes$1',
    '^@services(.*)$': '<rootDir>/src/services$1',
    '^@stores(.*)$': '<rootDir>/src/stores$1',
    '^@themes(.*)$': '<rootDir>/src/themes$1',
    '^@utils(.*)$': '<rootDir>/src/utils$1',
  },
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 80,
      functions: 80,
      lines: 80,
    },
  },
};
