export const NOTIFICATION_LIST = [
  {
    id: '1',
    sender: 'James Eusobio',
    description: 'send a new payment for',
    receiver: 'SEO',
    sentMoney: '$29.00',
    time: '23 mins ago',
    isMarkRead: false,
  },
  {
    id: '2',
    sender: 'Devon Lane',
    description: 'send a new payment for',
    receiver: 'HR',
    sentMoney: '$199.00',
    time: '5 mins ago',
    isMarkRead: true,
  },
  {
    id: '3',
    sender: 'Bessie Cooper',
    description: 'send a new payment for',
    receiver: 'CEO',
    sentMoney: '$10.00',
    time: '1 mins ago',
    isMarkRead: false,
  },
  {
    id: '4',
    sender: 'Fepaciy Russell',
    description: 'send a new payment for',
    receiver: 'SEO',
    sentMoney: '$1.00',
    time: '3 mins ago',
    isMarkRead: true,
  },
  {
    id: '5',
    sender: 'Somav Russell',
    description: 'send a new payment for',
    receiver: 'SEO',
    sentMoney: '$2.00',
    time: '10 mins ago',
    isMarkRead: true,
  },
];
